# Generated by Django 3.0.7 on 2020-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessaging', '0002_auto_20200825_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Message Body'),
        ),
    ]
