# Generated by Django 3.0.7 on 2020-09-08 22:42

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('site_url', models.CharField(max_length=150)),
                ('code_url', models.CharField(max_length=150)),
                ('featured', models.BooleanField(default=False)),
                ('testimonial', models.TextField(blank=True)),
                ('reviewer', models.CharField(max_length=120)),
                ('created', models.DateField(blank=True)),
                ('practice', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
