# Generated by Django 3.0.7 on 2020-06-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200629_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tech_stack',
            field=models.CharField(default='python', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(),
        ),
    ]
