# Generated by Django 3.0.7 on 2020-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200818_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
