# Generated by Django 3.0.7 on 2020-08-23 03:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200820_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
