# Generated by Django 3.0.7 on 2020-08-23 03:06

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20200823_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='main_content',
            field=django_quill.fields.QuillField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(),
        ),
    ]
