# Generated by Django 3.0.7 on 2020-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_remove_job_main_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='practice',
            field=models.BooleanField(default=False),
        ),
    ]
