# Generated by Django 3.2.3 on 2021-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='main_content',
        ),
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
    ]
