# Generated by Django 3.2.4 on 2021-11-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
