# Generated by Django 3.2.4 on 2021-11-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211129_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-completed_date',)},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created',
            new_name='completed_date',
        ),
    ]
