# Generated by Django 3.2.4 on 2021-11-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('projects', '0005_auto_20211129_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Project',
        ),
    ]
