# Generated by Django 3.2.4 on 2021-12-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_job_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='testimonial',
        ),
    ]
