# Generated by Django 3.0.7 on 2020-08-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200825_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.Service'),
            preserve_default=False,
        ),
    ]
