# Generated by Django 3.0.7 on 2020-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200825_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(related_name='projects', to='dashboard.Service'),
        ),
    ]
