# Generated by Django 3.0.7 on 2020-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6),
            preserve_default=False,
        ),
    ]
