# Generated by Django 3.0.7 on 2020-08-15 02:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile-images/'),
        ),
    ]
