# Generated by Django 3.0.7 on 2020-08-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200815_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
