# Generated by Django 3.2.4 on 2021-12-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_rename_job_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_photo', models.ImageField(blank=True, upload_to='images/')),
                ('reviewer_name', models.CharField(max_length=120)),
                ('review_body', models.TextField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='projects.project')),
            ],
        ),
    ]
